---
title: "Tweets"
author: "Anand Mayakonda"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Tweets

I tweet the plots and base R tips and gotchas [@baseRgraphics](https://twitter.com/baseRgraphics). Follow me there for updates.


<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Migration to the US by world region between 1820-2009 - visualized as <a href="https://twitter.com/hashtag/areachart?src=hash&amp;ref_src=twsrc%5Etfw">#areachart</a> in base R.<a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/Datavisualization?src=hash&amp;ref_src=twsrc%5Etfw">#Datavisualization</a> <a href="https://t.co/U2VaDtskwD">https://t.co/U2VaDtskwD</a> <a href="https://t.co/0vKCDAcVSF">pic.twitter.com/0vKCDAcVSF</a></p>&mdash; basegRaphics (@baseRgraphics) <a href="https://twitter.com/baseRgraphics/status/1547524376911720448?ref_src=twsrc%5Etfw">July 14, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Visualizing the 20th German Bundestag results as a <a href="https://twitter.com/hashtag/ParliamentPlot?src=hash&amp;ref_src=twsrc%5Etfw">#ParliamentPlot</a> in pure base R.<a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/Datavisualization?src=hash&amp;ref_src=twsrc%5Etfw">#Datavisualization</a> <a href="https://t.co/U2VaDtskwD">https://t.co/U2VaDtskwD</a> <a href="https://t.co/XLOsJd1i77">pic.twitter.com/XLOsJd1i77</a></p>&mdash; basegRaphics (@baseRgraphics) <a href="https://twitter.com/baseRgraphics/status/1547188076736262144?ref_src=twsrc%5Etfw">July 13, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Recreating the popular measles vaccination plot by the <a href="https://twitter.com/WSJ?ref_src=twsrc%5Etfw">@WSJ</a> in base R (without any heatmap functions) <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/Datavisualization?src=hash&amp;ref_src=twsrc%5Etfw">#Datavisualization</a> <a href="https://t.co/U2VaDtskwD">https://t.co/U2VaDtskwD</a> <a href="https://t.co/m0am21wmgu">pic.twitter.com/m0am21wmgu</a></p>&mdash; basegRaphics (@baseRgraphics) <a href="https://twitter.com/baseRgraphics/status/1546803651552808961?ref_src=twsrc%5Etfw">July 12, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The richer, the healthier? Visualizing gapminder dataset as a <a href="https://twitter.com/hashtag/bubbleplot?src=hash&amp;ref_src=twsrc%5Etfw">#bubbleplot</a> in base R. <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/Datavisualization?src=hash&amp;ref_src=twsrc%5Etfw">#Datavisualization</a> <a href="https://t.co/U2VaDtskwD">https://t.co/U2VaDtskwD</a> <a href="https://t.co/Xuc4fd7MrR">pic.twitter.com/Xuc4fd7MrR</a></p>&mdash; basegRaphics (@baseRgraphics) <a href="https://twitter.com/baseRgraphics/status/1546416753961340929?ref_src=twsrc%5Etfw">July 11, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The rise and fall of cigarette consumption are visualized as <a href="https://twitter.com/hashtag/linechart?src=hash&amp;ref_src=twsrc%5Etfw">#linechart</a> using base graphics. <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/Datavisualization?src=hash&amp;ref_src=twsrc%5Etfw">#Datavisualization</a> <a href="https://t.co/U2VaDtKtKL">https://t.co/U2VaDtKtKL</a> <a href="https://t.co/FirzPAlAnV">pic.twitter.com/FirzPAlAnV</a></p>&mdash; basegRaphics (@baseRgraphics) <a href="https://twitter.com/baseRgraphics/status/1545405789535612928?ref_src=twsrc%5Etfw">July 8, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Frequency of <a href="https://twitter.com/hashtag/COVID19?src=hash&amp;ref_src=twsrc%5Etfw">#COVID19</a> articles over the years <a href="https://twitter.com/biorxivpreprint?ref_src=twsrc%5Etfw">@biorxivpreprint</a> and <a href="https://twitter.com/medrxivpreprint?ref_src=twsrc%5Etfw">@medrxivpreprint</a> visualized as <a href="https://twitter.com/hashtag/lineplot?src=hash&amp;ref_src=twsrc%5Etfw">#lineplot</a> using pure base graphics <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/Datavisualization?src=hash&amp;ref_src=twsrc%5Etfw">#Datavisualization</a> <a href="https://t.co/U2VaDtKtKL">https://t.co/U2VaDtKtKL</a> <a href="https://t.co/FKjkRwy3JR">pic.twitter.com/FKjkRwy3JR</a></p>&mdash; basegRaphics (@baseRgraphics) <a href="https://twitter.com/baseRgraphics/status/1544924464353525760?ref_src=twsrc%5Etfw">July 7, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Wealth distribution among selected countries visualized as <a href="https://twitter.com/hashtag/donutplots?src=hash&amp;ref_src=twsrc%5Etfw">#donutplots</a> using pure base graphics <a href="https://twitter.com/hashtag/Rstats?src=hash&amp;ref_src=twsrc%5Etfw">#Rstats</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://t.co/U2VaDtKtKL">https://t.co/U2VaDtKtKL</a> <a href="https://t.co/evT4tqmtD1">pic.twitter.com/evT4tqmtD1</a></p>&mdash; basegRaphics (@baseRgraphics) <a href="https://twitter.com/baseRgraphics/status/1544920043078975488?ref_src=twsrc%5Etfw">July 7, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The median population age of selected countries visualized as <a href="https://twitter.com/hashtag/DumbbellPlot?src=hash&amp;ref_src=twsrc%5Etfw">#DumbbellPlot</a> in base <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://t.co/U2VaDtKtKL">https://t.co/U2VaDtKtKL</a> <a href="https://t.co/1YoJuhVITw">pic.twitter.com/1YoJuhVITw</a></p>&mdash; basegRaphics (@baseRgraphics) <a href="https://twitter.com/baseRgraphics/status/1544919025800847360?ref_src=twsrc%5Etfw">July 7, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
